
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Delete extends javax.swing.JFrame {
    Connection con= MyConnection.connectdb();
    PreparedStatement ps=null;
    ResultSet rs=null;

    /**
     * Creates new form Delete
     */
    public Delete() {
        initComponents();
        MyConnection.connectdb();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        button_delete = new java.awt.Button();
        button_Cancel = new java.awt.Button();
        textField_uname = new java.awt.TextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(0, 153, 153));
        label1.setText("Username :");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, 30));

        button_delete.setBackground(new java.awt.Color(0, 102, 102));
        button_delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_delete.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button_delete.setForeground(new java.awt.Color(255, 255, 255));
        button_delete.setLabel("Delete");
        button_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(button_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        button_Cancel.setBackground(new java.awt.Color(153, 0, 0));
        button_Cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_Cancel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button_Cancel.setForeground(new java.awt.Color(255, 255, 255));
        button_Cancel.setLabel("Cancel");
        button_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_CancelActionPerformed(evt);
            }
        });
        getContentPane().add(button_Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        textField_uname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textField_uname.setForeground(new java.awt.Color(0, 0, 0));
        textField_uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_unameActionPerformed(evt);
            }
        });
        getContentPane().add(textField_uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 146, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_deleteActionPerformed

        
        String uname = textField_uname.getText();

        if (uname.equals("")){
            JOptionPane.showMessageDialog(null,"Add a User Name");
        }

        else {
            PreparedStatement ps;
            String query = "DELETE FROM TENATSPROFILE WHERE user_Name = ?";

            try {
                ps = MyConnection.connectdb().prepareStatement(query);

                
                ps.setString(1, uname);

                if(ps.executeUpdate()>0){
                    JOptionPane.showMessageDialog(null,"Data Deleted");
                    dispose();

                }

            } catch (SQLException ex) {
                Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_button_deleteActionPerformed

    private void button_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_CancelActionPerformed
        dispose();
        new WelcomeBox().setVisible(true);
    }//GEN-LAST:event_button_CancelActionPerformed

    private void textField_unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_unameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button_Cancel;
    private java.awt.Button button_delete;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.TextField textField_uname;
    // End of variables declaration//GEN-END:variables
}
