
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Insert extends javax.swing.JFrame {
    Connection con= MyConnection.connectdb();
    PreparedStatement ps=null;
    ResultSet rs=null;

    /**
     * Creates new form Insert
     */
    public Insert() {
        initComponents();
        //this.setLocationRelativeTo(null);
        MyConnection.connectdb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label4 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        textField_phone = new java.awt.TextField();
        button_save = new java.awt.Button();
        button_Cancel = new java.awt.Button();
        label3 = new java.awt.Label();
        label5 = new java.awt.Label();
        textField_uname = new java.awt.TextField();
        textField_town = new java.awt.TextField();
        textField_address = new java.awt.TextField();

        label4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label4.setForeground(new java.awt.Color(0, 153, 153));
        label4.setText("New Password :");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(214, 234, 248));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(0, 153, 153));
        label1.setText("Username :");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 49, -1, -1));

        label2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label2.setForeground(new java.awt.Color(0, 153, 153));
        label2.setText("Phone:");
        jPanel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 98, -1, -1));

        textField_phone.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textField_phone.setForeground(new java.awt.Color(0, 0, 0));
        textField_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_phoneActionPerformed(evt);
            }
        });
        jPanel1.add(textField_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 101, 146, -1));

        button_save.setBackground(new java.awt.Color(0, 102, 102));
        button_save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_save.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button_save.setForeground(new java.awt.Color(255, 255, 255));
        button_save.setLabel("Save");
        button_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_saveActionPerformed(evt);
            }
        });
        jPanel1.add(button_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 263, -1, -1));

        button_Cancel.setBackground(new java.awt.Color(153, 0, 0));
        button_Cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_Cancel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button_Cancel.setForeground(new java.awt.Color(255, 255, 255));
        button_Cancel.setLabel("Cancel");
        button_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_CancelActionPerformed(evt);
            }
        });
        jPanel1.add(button_Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 263, -1, -1));

        label3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label3.setForeground(new java.awt.Color(0, 153, 153));
        label3.setText("Address :");
        jPanel1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 139, -1, -1));

        label5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label5.setForeground(new java.awt.Color(0, 153, 153));
        label5.setText("Town :");
        jPanel1.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 206, -1, -1));

        textField_uname.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textField_uname.setForeground(new java.awt.Color(0, 0, 0));
        textField_uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_unameActionPerformed(evt);
            }
        });
        jPanel1.add(textField_uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 52, 146, -1));

        textField_town.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textField_town.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(textField_town, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 209, 146, -1));

        textField_address.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textField_address.setForeground(new java.awt.Color(0, 0, 0));
        textField_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_addressActionPerformed(evt);
            }
        });
        jPanel1.add(textField_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 142, 146, 49));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, -2, 470, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_saveActionPerformed

        
        
        String phone = textField_phone.getText();
        String add = textField_address.getText();
        String town = textField_town.getText();
        String uname = textField_uname.getText();

        
        if (uname.equals("")){
            JOptionPane.showMessageDialog(null,"Add a User Name");
        }
        
        else {
        PreparedStatement ps;
        String query = "UPDATE TENATSPROFILE SET phone=? ,address=? ,Town=?  WHERE user_Name = ?";
        
        try {
            ps = MyConnection.connectdb().prepareStatement(query);
            
            
            ps.setString(1, phone);
            ps.setString(2, add);
            ps.setString(3, town);
            ps.setString(4, uname);
            
            
            
            
            if(ps.executeUpdate()>0){
                JOptionPane.showMessageDialog(null,"Info Added"); 
                dispose();
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        }

    }//GEN-LAST:event_button_saveActionPerformed

    private void button_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_CancelActionPerformed
        dispose();
        new WelcomeBox().setVisible(true);
    }//GEN-LAST:event_button_CancelActionPerformed

    private void textField_unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_unameActionPerformed

    private void textField_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_addressActionPerformed

    private void textField_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_phoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Insert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button_Cancel;
    private java.awt.Button button_save;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.TextField textField_address;
    private java.awt.TextField textField_phone;
    private java.awt.TextField textField_town;
    private java.awt.TextField textField_uname;
    // End of variables declaration//GEN-END:variables
}
