
import java.awt.Component;
import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Rent extends javax.swing.JFrame {

    /**
     * Creates new form Rent
     */
    public Rent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        label5 = new java.awt.Label();
        jPanel8 = new javax.swing.JPanel();
        label2 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        jtxtProveofID = new javax.swing.JComboBox<>();
        label16 = new java.awt.Label();
        label17 = new java.awt.Label();
        label18 = new java.awt.Label();
        jtxtSurname = new javax.swing.JTextField();
        jtxtTown = new javax.swing.JTextField();
        jtxtFirstname = new javax.swing.JTextField();
        jtxtCustomer = new javax.swing.JTextField();
        jtxtDeposit = new javax.swing.JTextField();
        jtxtPostCode = new javax.swing.JTextField();
        label19 = new java.awt.Label();
        label20 = new java.awt.Label();
        jtxtAdrress = new javax.swing.JTextField();
        jtxtDownPayment = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jrtReceipt = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        label3 = new java.awt.Label();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        label11 = new java.awt.Label();
        jComboBox1 = new javax.swing.JComboBox<>();
        jtxtnumberofroom = new javax.swing.JComboBox<>();
        jtxtCost = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        label4 = new java.awt.Label();
        label12 = new java.awt.Label();
        label13 = new java.awt.Label();
        label14 = new java.awt.Label();
        label15 = new java.awt.Label();
        jtxtLocalTax = new javax.swing.JTextField();
        jtxtWaterBill = new javax.swing.JTextField();
        jtxtTotalPayment = new javax.swing.JTextField();
        jtxtElectricity = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 12));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        label1.setText("Rent Management System");
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 22, -1, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1290, 120));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 12));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        label5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label5.setText("Customer Details");
        jPanel7.add(label5);

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 140, 40));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        label2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label2.setText("Proof Of ID");
        jPanel8.add(label2);

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 190, 40));

        label6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label6.setText("Deposit");
        jPanel2.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, -1, -1));

        label7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label7.setText("First Name");
        jPanel2.add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        label8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label8.setText("Surname");
        jPanel2.add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jtxtProveofID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtxtProveofID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Birth Certificate", "National ID", "Passport", "Driving License", "Student ID" }));
        jtxtProveofID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.add(jtxtProveofID, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 130, 30));

        label16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label16.setText("Post Code");
        jPanel2.add(label16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        label17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label17.setText("Town");
        jPanel2.add(label17, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, -1));

        label18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label18.setText("Customer ID");
        jPanel2.add(label18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jtxtSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSurnameActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 130, -1));

        jtxtTown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTownActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtTown, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 130, -1));

        jtxtFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFirstnameActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 130, -1));

        jtxtCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCustomerActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 130, -1));

        jtxtDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDepositActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtDeposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, 130, -1));

        jtxtPostCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPostCodeActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtPostCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 130, -1));

        label19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label19.setText("Adress");
        jPanel2.add(label19, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        label20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label20.setText("Down Payment");
        jPanel2.add(label20, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, -1, -1));

        jtxtAdrress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtAdrressActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtAdrress, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 130, -1));

        jtxtDownPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDownPaymentActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtDownPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, 130, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 840, 260));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 12));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jrtReceipt.setColumns(20);
        jrtReceipt.setRows(5);
        jScrollPane1.setViewportView(jrtReceipt);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 400, 400));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 140, 440, 440));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 12));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        label3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label3.setText("Rental Details");
        jPanel9.add(label3);

        jPanel4.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 160, 40));

        label9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label9.setText("Cost");
        jPanel4.add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        label10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label10.setText("Number of Rooms");
        jPanel4.add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        label11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label11.setText("Location");
        jPanel4.add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gulshan", "Banani", "Farmgate" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 130, 30));

        jtxtnumberofroom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtxtnumberofroom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        jtxtnumberofroom.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.add(jtxtnumberofroom, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 130, 30));

        jtxtCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCostActionPerformed(evt);
            }
        });
        jPanel4.add(jtxtCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 130, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 400, 260));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 12));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        label4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label4.setText("Utility Bills");
        jPanel10.add(label4);

        jPanel3.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 150, 40));

        label12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label12.setText("Electricity");
        jPanel3.add(label12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        label13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label13.setText("Local Tax");
        jPanel3.add(label13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        label14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label14.setText("Water Bill");
        jPanel3.add(label14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        label15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label15.setText("Total Payment");
        jPanel3.add(label15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jtxtLocalTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtLocalTaxActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtLocalTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 130, -1));

        jtxtWaterBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtWaterBillActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtWaterBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 130, -1));

        jtxtTotalPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalPaymentActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtTotalPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 130, -1));

        jtxtElectricity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtElectricityActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtElectricity, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 130, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, 430, 260));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 12));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Exit");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 30, 70, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Rental");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 60, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Print");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 70, 30));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Reset");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 60, 30));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 590, 440, 80));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private JFrame frame;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        try {
            jrtReceipt.print();
        } catch (PrinterException ex) {
            Logger.getLogger(Rent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jtxtLocalTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtLocalTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtLocalTaxActionPerformed

    private void jtxtCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCostActionPerformed

    private void jtxtWaterBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtWaterBillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtWaterBillActionPerformed

    private void jtxtTotalPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalPaymentActionPerformed

    private void jtxtSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSurnameActionPerformed

    private void jtxtElectricityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtElectricityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtElectricityActionPerformed

    private void jtxtTownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTownActionPerformed

    private void jtxtFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFirstnameActionPerformed

    private void jtxtCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCustomerActionPerformed

    private void jtxtDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDepositActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDepositActionPerformed

    private void jtxtPostCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPostCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPostCodeActionPerformed

    private void jtxtAdrressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAdrressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtAdrressActionPerformed

    private void jtxtDownPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDownPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDownPaymentActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit","Rent Management System",
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JTextField cleartext=null;
        
        for (Component c:jPanel2.getComponents()){
            if(c.getClass().toString().contains("javax.swing.JTextField")){
                cleartext = (JTextField)c;
                cleartext.setText("");
                jtxtCost.setText("");
                jrtReceipt.setText("");
            }
        }
        
        
        
        for (Component c:jPanel3.getComponents()){
            if(c.getClass().toString().contains("javax.swing.JTextField")){
                cleartext = (JTextField)c;
                cleartext.setText("");
            }
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        cCustomer iCustomer = new cCustomer();
        cRental iRental = new cRental();
        cUtilities iUtilities = new cUtilities();
        
        double iCustDeposit , iCustPayment = 0, icost, inumberofroom, ilocalTax, iwaterBill, ielectricity;
        String strCost;
        
        iCustDeposit = Double.parseDouble(jtxtDeposit.getText());
        iCustPayment = Double.parseDouble(jtxtDownPayment.getText());
        icost = Double.parseDouble(jtxtCost.getText());
        
        ielectricity = Double.parseDouble(jtxtElectricity.getText());
        iwaterBill = Double.parseDouble(jtxtWaterBill.getText());
        ilocalTax = Double.parseDouble(jtxtLocalTax.getText());
        
        
        
        iCustomer.setDeposit(iCustDeposit);
        iCustomer.setDownPayment(iCustPayment);
        iRental.setCost(icost);
        iUtilities.setElectricity(ielectricity);
        iUtilities.setLocalTax(ilocalTax);
        iUtilities.setWaterBill(iwaterBill);
        
        strCost = String.format("%.2f", iCustomer.getDeposit() + iCustomer.getDownPayment() + iRental.getCost() + iUtilities.getElectricity() + 
                  iUtilities.getLocalTax() + iUtilities.getWaterBill() );
        jtxtTotalPayment.setText(strCost);
        
        jrtReceipt.append("\tRent Management System"+"\n" +
        "------------------------------------------------------------------------"+"\n");
        jrtReceipt.append("Customer ID" + "\t\t\t"+jtxtCustomer.getText()+ "\n");
        jrtReceipt.append("Firstname" + "\t\t\t"+jtxtFirstname.getText()+ "\n");
        jrtReceipt.append("Surname" + "\t\t\t"+jtxtSurname.getText()+ "\n");
        jrtReceipt.append("Adrress" + "\t\t\t"+jtxtAdrress.getText()+ "\n");
        jrtReceipt.append("Post Code" + "\t\t\t"+jtxtPostCode.getText()+ "\n");
        jrtReceipt.append("Prove of ID" + "\t\t\t"+jtxtProveofID.getSelectedItem()+ "\n");
        jrtReceipt.append("Town" + "\t\t\t"+jtxtTown.getText()+ "\n");
        jrtReceipt.append("------------------------------------------------------------------------"+"\n");
        jrtReceipt.append("Deposit" + "\t\t\t"+jtxtDeposit.getText()+ "\n");
        jrtReceipt.append("Down Payment" + "\t\t\t"+jtxtDownPayment.getText()+ "\n");
        jrtReceipt.append("Number of Room" + "\t\t\t"+jtxtnumberofroom.getSelectedItem()+ "\n");
        
        jrtReceipt.append("Electricity" + "\t\t\t"+jtxtElectricity.getText()+ "\n");
        jrtReceipt.append("Local Bill" + "\t\t\t"+jtxtLocalTax.getText()+ "\n");
        jrtReceipt.append("Water Bill" + "\t\t\t"+jtxtWaterBill.getText()+ "\n");
        jrtReceipt.append("------------------------------------------------------------------------"+"\n");
        jrtReceipt.append("Total Payment" + "\t\t\t"+jtxtTotalPayment.getText()+ "\n");
        jrtReceipt.append("------------------------------------------------------------------------"+"\n");
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jrtReceipt;
    private javax.swing.JTextField jtxtAdrress;
    private javax.swing.JTextField jtxtCost;
    private javax.swing.JTextField jtxtCustomer;
    private javax.swing.JTextField jtxtDeposit;
    private javax.swing.JTextField jtxtDownPayment;
    private javax.swing.JTextField jtxtElectricity;
    private javax.swing.JTextField jtxtFirstname;
    private javax.swing.JTextField jtxtLocalTax;
    private javax.swing.JTextField jtxtPostCode;
    private javax.swing.JComboBox<String> jtxtProveofID;
    private javax.swing.JTextField jtxtSurname;
    private javax.swing.JTextField jtxtTotalPayment;
    private javax.swing.JTextField jtxtTown;
    private javax.swing.JTextField jtxtWaterBill;
    private javax.swing.JComboBox<String> jtxtnumberofroom;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label18;
    private java.awt.Label label19;
    private java.awt.Label label2;
    private java.awt.Label label20;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    // End of variables declaration//GEN-END:variables
}
